### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by github4maninder**
rename the branch from master to main

### CODE REVIEW

**Comment by sibelius** [comment]
not the right way of doing it

**Comment by github4maninder** [comment]
thank you for your response. if possible, I would love to learn what is the proper way of changing the branch name. I was not able to create a pull request as it showed that there was no changes made(while I just changed the name of the branch). so i had to add an extra line in the readme then i was able to open a PR.

**Comment by sibelius** [comment]
The process is go inside branches, and then edit directly on GitHub from master to main

I think only repo admins can do that

**Comment by github4maninder** [comment]
thanks for the info

**Pull request closed without merging**
